### ISSUE TITLE
تصمیم گیری در مورد target و type و تداخل داخل تگ فرم form

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam#234]

**Comment by BaseMax** [comment]
I will have a think about it.

**Comment by BaseMax** [comment]
اعمال شد:
```
  - id: AST_LAYOUT_ATTRIBUTE_TYPE_TYPE
    generate_name: type
    text:
      en: type
      fa: نوع
  - id: AST_LAYOUT_ATTRIBUTE_TYPE_KIND
    generate_name: kind
    text:
      en: kind
      fa: روش
```
